version: "3"

services:
  react-app:
    container_name: client-container
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    container_name: server-container
    image: api-server
    ports:
      - "3080:3080"
    networks:
      - mern-app
  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  
